FROM python:3.13-slim AS builder

WORKDIR /app

RUN pip install --no-cache-dir poetry
COPY sonia-emu/webui/pyproject.toml sonia-emu/webui/poetry.lock ./
RUN poetry config virtualenvs.create false \
    && poetry install --only main --no-interaction --no-ansi


FROM python:3.13-slim AS runtime

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

RUN groupadd -r app && useradd -r -g app app

COPY --chown=app:app sonia-emu/webui/src/ .

ENV PYTHONUNBUFFERED=1

USER app
